In [1]:
import cv2
import numpy as np
import glob
import random

In [2]:
# Load Yolo
net = cv2.dnn.readNet("11yolov3_training_last.weights", "5yolov3_testing.cfg")
# net = cv2.dnn.readNet("3yolov3_training_4000.weights", "2yolov3_testing.cfg")

# Name custom object
classes = ["V","A","H","V","A"]

# Images path
# images_path = glob.glob(r"C:\Users\Craigdon\Desktop\codes\yolov3\Eczema\*.jpg")
images_path = glob.glob(r"C:/Users/kraji/Desktop/Codes/YOLOv3/TrainingSet/Testing/*.jpg")


In [3]:
layer_names = net.getLayerNames()
output_layers = [layer_names[i[0] - 1] for i in net.getUnconnectedOutLayers()]
colors = np.random.uniform(0, 255, size=(len(classes), 3))

In [4]:
# Insert here the path of your images
random.shuffle(images_path)
# loop through all the images
for img_path in images_path:
    # Loading image
    img = cv2.imread(img_path)
    img = cv2.resize(img, None, fx=0.4, fy=0.4)
    # Convert to grayscale
#     img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    height, width, channels = img.shape

    # Detecting objects
    blob = cv2.dnn.blobFromImage(img, 0.00392, (480, 480), (0, 0, 0), True, crop=False)

    net.setInput(blob)
    outs = net.forward(output_layers)

    # Showing informations on the screen
    class_ids = []
    confidences = []
    boxes = []
    for out in outs:
        for detection in out:
            scores = detection[5:]
            class_id = np.argmax(scores)
            confidence = scores[class_id]
            if confidence > 0.3:
                # Object detected
                print(class_id)
                center_x = int(detection[0] * width)
                center_y = int(detection[1] * height)
                w = int(detection[2] * width)
                h = int(detection[3] * height)

                # Rectangle coordinates
                x = int(center_x - w / 2)
                y = int(center_y - h / 2)

                boxes.append([x, y, w, h])
                confidences.append(float(confidence))
                class_ids.append(class_id)

    indexes = cv2.dnn.NMSBoxes(boxes, confidences, 0.5, 0.4)
    print(indexes)
    font = cv2.FONT_HERSHEY_PLAIN
    for i in range(len(boxes)):
        if i in indexes:
            x, y, w, h = boxes[i]
            label = str(classes[class_ids[i]])
            color = colors[class_ids[i]]
            cv2.rectangle(img, (x, y), (x + w, y + h), color, 0)
            cv2.putText(img, label, (x, y + 30), font, 1, color, 1)

    cv2.namedWindow('Image', 600)
#     cv2.resizeWindow('Image', 600, 600)
    cv2.imshow("Image", img)
    key = cv2.waitKey(0)

cv2.destroyAllWindows()

()
()
2
2
2
2
2
[[1]
 [3]
 [0]
 [4]
 [2]]
0
0
3
[[1]]
()
2
[[0]]
3
3
[[1]]
0
0
[[0]
 [1]]
4
4
4
[[2]
 [1]
 [0]]
0
0
[[1]]
3
3
3
[[0]
 [2]
 [1]]
3
3
3
3
3
3
3
3
3
[[1]
 [7]
 [3]
 [4]
 [2]
 [5]
 [0]
 [8]
 [6]]
0
0
0
0
0
0
0
0
0
0
0
[[3]
 [1]
 [4]
 [8]
 [7]
 [9]]
3
[[0]]
2
2
2
2
2
[[2]
 [3]
 [4]
 [0]]
