In [1]:
import logging
import sys
import numpy as np
import time
from scipy.io import loadmat
from keras.callbacks import LearningRateScheduler, ModelCheckpoint
from keras.utils import np_utils
from keras.models import Model, Sequential, load_model
from keras import backend as k
import matplotlib.pyplot as plt
from keras.layers import Input, Activation, Add, Dense, Flatten, Concatenate, Dropout, \
    Reshape, Multiply, Lambda, Subtract, ReLU, Conv2DTranspose, LeakyReLU
from keras.layers.convolutional import Conv2D, Conv3D, AveragePooling2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.regularizers import l2
from keras import backend as K
import tensorflow as tf
from keras.optimizers import SGD, Adam
from keras.datasets import mnist


In [45]:
##### sanitizer.h5 #####

from keras.models import load_model
import matplotlib.pyplot as plt
import numpy as np
import cv2

index = 136000;
# load model
model = load_model('./v3_Output/v3_1_1_4/1_1_4_'+str(index)+'_sanitizer.h5')

# show model i/o
input = model.input
output = model.output
print (input)
print (output)


imageindex = 6070# here to change image

# summarize model.
# model.summary()

def load_data():
    print("load_data()\n")
    d = loadmat('./UTKFace_Gray_AgeAbove3.mat')
    image, gender, age = d["image"], d["gender"][0], d["age"][0]
    print("Amount of images loaded = ", len(image))
    idx = np.where((age > 50) | (age < 20))[0]
    image = image[idx] / 255.0
    gender = gender[idx]
    age = age[idx]

    age = np.where(age > 30, 1, 0)
    age = np_utils.to_categorical(age, 2)
    gender = np_utils.to_categorical(gender, 2)

    return image, gender, age

# load dataset
image, gender, age = load_data()
img = image[imageindex : imageindex + 1]
print("input shape = "+str(img.shape) )
# imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
copyImg = img[0].copy()
resizeImg = copyImg.resize((200,200))
cv2.imshow("3", img[0])


# cv2.imshow("7", resizeImg)
# print("shape"+str(imgGray.shape))
# imgGray = cv2.resize(imgGray,(64,64))
# imgResize = imgGray.reshape(1,64,64,1) # see imgResize
# print("resize"+str(imgResize.shape))
# cv2.imshow("1", imgGray)

# create noise
#noise_in = np.random.normal(0, 1, (1, 64, 64, 1))
noise_in = np.random.normal(0, 1, (1, 16, 16, 1))
# noise_pic = noise_in.reshape(22,22)
# cv2.imshow("2", noise_pic)

print("noise"+str(noise_in.shape))

# evaluate the model
score = model.predict([noise_in,img])
print ("output shape = "+str(score.shape))
# cropped = score[0,0:64,0:64,0]
OUTPUT = score.reshape(64,64)
# resizeOUTPUT = OUTPUT.resize(200,200)
print ("output shape after = "+str(OUTPUT.shape))
# cropped = cv2.resize(cropped,(64,64))
# OUTPUT = cv2.resize(OUTPUT,(600,600))

#debug
# print(noise_in)
# cv2.imshow('3', cropped)
cv2.imshow('sample image', OUTPUT)
# cv2.imshow('resized image', resizeOUTPUT)

cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image


[<KerasTensor: shape=(None, 16, 16, 1) dtype=float32 (created by layer 'input_1')>, <KerasTensor: shape=(None, 64, 64, 1) dtype=float32 (created by layer 'input_2')>]
KerasTensor(type_spec=TensorSpec(shape=(None, 64, 64, 1), dtype=tf.float32, name=None), name='conv2d_transpose_1/Sigmoid:0', description="created by layer 'conv2d_transpose_1'")
load_data()

Amount of images loaded =  21814
input shape = (1, 64, 64, 1)
noise(1, 16, 16, 1)
output shape = (1, 64, 64, 1)
output shape after = (64, 64)


In [4]:
array = [[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]]
array = np.array(array)
print(array.shape)

(3, 3, 1)


In [5]:
import numpy as np
arr=np.empty((9,9,4))
print(arr.shape)
counter = 0

for i in range(9):
    for j in range(9):
        for k in range (4):
            arr[i][j][k] = counter
            counter += 1
# print(arr)
# imgResize = imgGray.reshape(64,64,64,1) # see imgResize
arr = arr.reshape(18,18,1)
print(arr.shape)
print(arr[3][0][0])
print(arr)


#conclusion = reshape will reshape using index from right to left of arr[3rd][2nd][1st].

(9, 9, 4)
(18, 18, 1)
54.0
[[[  0.]
  [  1.]
  [  2.]
  [  3.]
  [  4.]
  [  5.]
  [  6.]
  [  7.]
  [  8.]
  [  9.]
  [ 10.]
  [ 11.]
  [ 12.]
  [ 13.]
  [ 14.]
  [ 15.]
  [ 16.]
  [ 17.]]

 [[ 18.]
  [ 19.]
  [ 20.]
  [ 21.]
  [ 22.]
  [ 23.]
  [ 24.]
  [ 25.]
  [ 26.]
  [ 27.]
  [ 28.]
  [ 29.]
  [ 30.]
  [ 31.]
  [ 32.]
  [ 33.]
  [ 34.]
  [ 35.]]

 [[ 36.]
  [ 37.]
  [ 38.]
  [ 39.]
  [ 40.]
  [ 41.]
  [ 42.]
  [ 43.]
  [ 44.]
  [ 45.]
  [ 46.]
  [ 47.]
  [ 48.]
  [ 49.]
  [ 50.]
  [ 51.]
  [ 52.]
  [ 53.]]

 [[ 54.]
  [ 55.]
  [ 56.]
  [ 57.]
  [ 58.]
  [ 59.]
  [ 60.]
  [ 61.]
  [ 62.]
  [ 63.]
  [ 64.]
  [ 65.]
  [ 66.]
  [ 67.]
  [ 68.]
  [ 69.]
  [ 70.]
  [ 71.]]

 [[ 72.]
  [ 73.]
  [ 74.]
  [ 75.]
  [ 76.]
  [ 77.]
  [ 78.]
  [ 79.]
  [ 80.]
  [ 81.]
  [ 82.]
  [ 83.]
  [ 84.]
  [ 85.]
  [ 86.]
  [ 87.]
  [ 88.]
  [ 89.]]

 [[ 90.]
  [ 91.]
  [ 92.]
  [ 93.]
  [ 94.]
  [ 95.]
  [ 96.]
  [ 97.]
  [ 98.]
  [ 99.]
  [100.]
  [101.]
  [102.]
  [103.]
  [104.]
  [105.]
  [106.]


In [15]:
import numpy as np
arr=np.empty((512,512))
print(arr.shape)
counter = 0

for i in range(512):
    for j in range(512):
        arr[i][j] = int(counter)
        counter += 1
print(arr[0][0])
arr = arr.reshape(64,64,64)
print(arr[0][0][0])
print(arr)

(512, 512)
0.0
0.0
[[[0.00000e+00 1.00000e+00 2.00000e+00 ... 6.10000e+01 6.20000e+01
   6.30000e+01]
  [6.40000e+01 6.50000e+01 6.60000e+01 ... 1.25000e+02 1.26000e+02
   1.27000e+02]
  [1.28000e+02 1.29000e+02 1.30000e+02 ... 1.89000e+02 1.90000e+02
   1.91000e+02]
  ...
  [3.90400e+03 3.90500e+03 3.90600e+03 ... 3.96500e+03 3.96600e+03
   3.96700e+03]
  [3.96800e+03 3.96900e+03 3.97000e+03 ... 4.02900e+03 4.03000e+03
   4.03100e+03]
  [4.03200e+03 4.03300e+03 4.03400e+03 ... 4.09300e+03 4.09400e+03
   4.09500e+03]]

 [[4.09600e+03 4.09700e+03 4.09800e+03 ... 4.15700e+03 4.15800e+03
   4.15900e+03]
  [4.16000e+03 4.16100e+03 4.16200e+03 ... 4.22100e+03 4.22200e+03
   4.22300e+03]
  [4.22400e+03 4.22500e+03 4.22600e+03 ... 4.28500e+03 4.28600e+03
   4.28700e+03]
  ...
  [8.00000e+03 8.00100e+03 8.00200e+03 ... 8.06100e+03 8.06200e+03
   8.06300e+03]
  [8.06400e+03 8.06500e+03 8.06600e+03 ... 8.12500e+03 8.12600e+03
   8.12700e+03]
  [8.12800e+03 8.12900e+03 8.13000e+03 ... 8.18900e+03

In [3]:
#Testing out down sizing.
# Question... will it crop or will it downsize
# imgGray = cv2.resize(imgGray,(64,64))

import cv2
import numpy as np
import glob
import random

img_path = "./MyFaceCrop.jpg"
img = cv2.imread(img_path)
# img = cv2.resize(img, None, fx=0.2, fy=0.2)interpolation = cv2.INTER_AREA
ResizedImage = cv2.resize(img, (64,64) , interpolation = cv2.INTER_AREA)
print(img.shape)
print(ResizedImage.shape)
cv2.imshow("3", img)
cv2.imshow("4", ResizedImage)

score = model.predict([noise_in, ResizedImage])
print ("output shape = "+str(score.shape))
# cropped = score[0,0:64,0:64,0]
OUTPUT = score.reshape(64,64)
print ("output shape after = "+str(OUTPUT.shape))
# cropped = cv2.resize(cropped,(64,64))
# OUTPUT = cv2.resize(OUTPUT,(600,600))

#debug
# print(noise_in)
# cv2.imshow('3', cropped)
cv2.imshow('sample image', OUTPUT)

cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image
# Answer: 

(1001, 625, 3)
(64, 64, 3)


ValueError: Error when checking input: expected input_2 to have 4 dimensions, but got array with shape (64, 64, 3)

In [11]:
##### sanitizer.h5 #####

from keras.models import load_model
import matplotlib.pyplot as plt
import numpy as np
import cv2
 
# load model
model = load_model('sanitizer_inv.h5')

# show model i/o
input = model.input
output = model.output
print (input)
print (output)

# summarize model.
# model.summary()

# def load_data():
#     print("load_data()\n")
#     d = loadmat('./UTKFace_Gray_AgeAbove3.mat')
#     image, gender, age = d["image"], d["gender"][0], d["age"][0]

#     idx = np.where((age > 50) | (age < 20))[0]
#     image = image[idx] / 255.0
#     gender = gender[idx]
#     age = age[idx]

#     age = np.where(age > 30, 1, 0)
#     age = np_utils.to_categorical(age, 2)
#     gender = np_utils.to_categorical(gender, 2)

#     return image, gender, age

# # load dataset
# image, gender, age = load_data()
# img = image[201:202]

img_path = "./MyFaceCrop.jpg"
image = cv2.imread(img_path)
# img = cv2.resize(img, None, fx=0.2, fy=0.2)interpolation = cv2.INTER_AREA
imgResize = cv2.resize(image, (64,64) , interpolation = cv2.INTER_AREA)


print("input shape = "+str(imgResize.shape) )
# imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("3", imgResize)
# print("shape"+str(imgGray.shape))
# imgGray = cv2.resize(imgGray,(64,64))
# imgResize = imgGray.reshape(1,64,64,1) # see imgResize
# print("resize"+str(imgResize.shape))
# cv2.imshow("1", imgGray)
imgGray = cv2.cvtColor(imgResize,cv2.COLOR_BGR2GRAY)
cv2.imshow("5", imgGray)
img = imgGray.reshape(1,64,64,1)

# cv2.imshow("4", img)

# create noise
noise_in = np.random.normal(0, 1, (1, 16, 16, 1))
# noise_pic = noise_in.reshape(22,22)
# cv2.imshow("2", noise_pic)

print("noise"+str(noise_in.shape))

# evaluate the model
score = model.predict([noise_in, img])
print ("output shape = "+str(score.shape))
# cropped = score[0,0:64,0:64,0]
OUTPUT = score.reshape(64,64)
print ("output shape after = "+str(OUTPUT.shape))
# cropped = cv2.resize(cropped,(64,64))
# OUTPUT = cv2.resize(OUTPUT,(600,600))

#debug
# print(noise_in)
# cv2.imshow('3', cropped)
cv2.imshow('sample image', OUTPUT)

cv2.waitKey(0) # waits until a key is pressed
cv2.destroyAllWindows() # destroys the window showing image


[<tf.Tensor 'input_1_9:0' shape=(None, 16, 16, 1) dtype=float32>, <tf.Tensor 'input_2_9:0' shape=(None, 64, 64, 1) dtype=float32>]
Tensor("conv2d_transpose_2_9/Sigmoid:0", shape=(None, None, None, 1), dtype=float32)
input shape = (64, 64, 3)
noise(1, 16, 16, 1)
output shape = (1, 64, 64, 1)
output shape after = (64, 64)
